import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import illustrationImg from "../illustration.png";
import { hexToRGBA } from "../utils/colorConverter";
import GitHubButton from "react-github-btn";
import '../styles/GlassmorphismContent.css'

export default function GlassmorphismContent({
  bgHexColor,
  bgOpacity,
  filterBlur,
  borderRadius,
  borderOpacity,
  codeBlockRef,
}) {
  return (
    <>
      <div className="glassmorphismContent py-5">
        <div className="text-center">
          <h2 className='glassmorphismContent_title'>GLASSMORPHISM GENERATOR</h2>
          <div className="mt-3">
            <GitHubButton
              href="https://github.com/deri-kurniawan"
              data-color-scheme="no-preference: light; light: dark_high_contrast; dark: dark;"
              data-size="large"
              data-show-count="true"
              aria-label="Follow @deri-kurniawan on GitHub"
              tabIndex={3}
            >
              Follow
            </GitHubButton>
            <GitHubButton
              href="https://github.com/deri-kurniawan/css-glassmorphism"
              data-color-scheme="no-preference: light; light: dark_high_contrast; dark: dark;"
              data-icon="octicon-star"
              data-size="large"
              data-show-count="true"
              aria-label="Star deri-kurniawan/css-glassmorphism on GitHub"
              tabIndex={3}
            >
              Star
            </GitHubButton>
            <GitHubButton
              href="https://github.com/deri-kurniawan/css-glassmorphism/issues"
              data-color-scheme="no-preference: light; light: dark_high_contrast; dark: dark;"
              data-icon="octicon-issue-opened"
              data-size="large"
              data-show-count="true"
              aria-label="Issue deri-kurniawan/css-glassmorphism on GitHub"
              tabIndex={3}
            >
              Issue
            </GitHubButton>
          </div>
        </div>
        <Container>
          <Row className="m-0 p-3 mb-3">
            <Col lg={6}>
              <img src={illustrationImg} className="col-12" alt="" />
            </Col>
            <Col lg={6}>
              <h3 className="text-left">CSS CODE</h3>
              <code className="card p-2" ref={codeBlockRef}>
                &#46;my-glass &#123;
                <br />
                &nbsp; &#47;&#42; Generated by
                https&#58;&#47;&#47;css&#45;glass&#46;vercel&#46;app&#47;
                &#42;&#47;
                <br />
                &nbsp; background&#45;color&#58;{" "}
                {hexToRGBA(bgHexColor, bgOpacity)}&#59;
                <br />
                &nbsp; backdrop&#45;filter&#58; blur({filterBlur}px);
                <br />
                &nbsp; &#45;webkit&#45;backdrop&#45;filter&#58; blur(
                {filterBlur}px)&#59;
                <br />
                &nbsp; box&#45;shadow&#58; 0 4px 30px rgba(0&#44; 0&#44; 0&#44;
                0&#46;1)&#59;
                <br />
                &nbsp; border&#45;radius&#58; {borderRadius}px&#59;
                <br />
                &nbsp; border&#58; 1px solid{" "}
                {hexToRGBA(bgHexColor, borderOpacity)}&#59;
                <br />
                &nbsp; width&#58; 100%&#59;
                <br />
                &nbsp; height&#58; 75px&#59;
                <br />
                &#125;
              </code>
            </Col>
          </Row>
          <Row className="m-0 p-3 mb-3">
            <Col xs={12} lg={6}>
              <h3>What is Google?</h3>
              <p>
                Google LLC is an American multinational corporation specializing
                in Internet services and products. These products include search
                technology, web computing, software, and online advertising.
                Most of its profits come from AdWords.
              </p>
            </Col>
            <Col xs={12} lg={6}>
              <img src={illustrationImg} className="col-12" alt="" />
            </Col>
          </Row>
        </Container>
      </div>
    </>
  );
}
